# Generated by Django 3.2.16 on 2022-10-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_alter_vehicle_wheel_count'), ('app', '0003_car_file'), ('app', '0004_delete_student'), ('app', '0005_alter_car_file'), ('app', '0006_alter_car_file'), ('app', '0007_dept_student'), ('app', '0008_alter_student_id'), ('app', '0009_alter_student_id'), ('app', '0010_club')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_number', models.CharField(max_length=20)),
                ('wheel_count', models.IntegerField(null=True)),
                ('manufacturer', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.vehicle')),
                ('max_goods_weight', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('app.vehicle',),
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.vehicle')),
                ('has_roof_top', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=' ')),
            ],
            bases=('app.vehicle',),
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.dept')),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
