# Generated by Django 3.2.16 on 2022-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_number', models.CharField(max_length=20)),
                ('wheel_count', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.vehicle')),
                ('has_roof_top', models.BooleanField(default=False)),
            ],
            bases=('app.vehicle',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.vehicle')),
                ('max_goods_weight', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('app.vehicle',),
        ),
    ]
