# Generated by Django 3.2.16 on 2022-10-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
