# Generated by Django 3.2.16 on 2022-10-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_car_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='file',
            field=models.FileField(upload_to=' '),
        ),
    ]
