# Generated by Django 3.2.16 on 2022-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_student_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['lp_number', 'manufacturer'], name='app_vehicle_lp_numb_15c9a3_idx'),
        ),
    ]
