# Generated by Django 3.2.16 on 2022-10-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vehicle_app_vehicle_lp_numb_15c9a3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clubs',
            field=models.ManyToManyField(to='app.club'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesscard', models.IntegerField()),
                ('departmentaccess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.dept')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='accesscard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.access'),
        ),
    ]
