# Generated by Django 3.2.16 on 2022-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='id',
        ),
        migrations.AlterField(
            model_name='example',
            name='data',
            field=models.JSONField(primary_key=True, serialize=False),
        ),
    ]
