# Generated by Django 3.2.16 on 2022-10-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20221026_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
