# Generated by Django 3.2.16 on 2022-10-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
