# Generated by Django 3.2.16 on 2022-10-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20221027_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='customer',
        ),
    ]
