# Generated by Django 3.2.16 on 2022-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='branch',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
